jobs:
  checkstyle_job:
    name: Create checkstyle report
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Run check style (core)
      run: ./gradlew javacord-core:checkstyleMain
    - continue-on-error: true
      name: Run check style (api)
      run: ./gradlew javacord-api:checkstyleMain
    - continue-on-error: true
      name: Setup Reviewdog
      uses: reviewdog/action-setup@v1
    - continue-on-error: true
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Run reviewdog
      run: cat javacord-core/build/reports/checkstyle/main.xml \ | reviewdog -f=checkstyle
        -name="Check style (core)" -reporter=github-pr-check -filter-mode="nofilter"
        \ && cat javacord-api/build/reports/checkstyle/main.xml \ | reviewdog -f=checkstyle
        -name="Check style (api)" -reporter=github-pr-check -filter-mode="nofilter"
name: Codestyle
on:
  repository_dispatch:
    types: trigger-ga___checkstyle.yml
