jobs:
  build-and-test:
    name: Build and test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: 'echo "No build required" '
name: Main
on:
  repository_dispatch:
    types: trigger-ga___main_allcontributors.yml
