jobs:
  build-and-test:
    name: Build and test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Build project
      run: ./gradlew build -x test
    - continue-on-error: true
      name: Run tests
      run: ./gradlew test
name: Main
on:
  repository_dispatch:
    types: trigger-ga___main.yml
