jobs:
  build:
    name: Prepare Release - Update Readme and Remove Snapshot Suffix
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Remove Snapshot Suffix
      run: 'sed -i -E "s/(version \= .*)-SNAPSHOT/\1/g" gradle.properties

        '
    - continue-on-error: true
      name: Update Readme File
      run: './gradlew updateReadme

        '
    - continue-on-error: true
      id: read-version
      name: Read Version
      run: 'version=`cat gradle.properties | sed -n "s/^.*version\s*=\s*\(\S*\).*$/\1/p"`

        echo "::set-output name=version::$version"

        '
    - continue-on-error: true
      name: Commit Release Version
      run: 'git config --global user.name ''github-actions[bot]''

        git config --global user.email ''41898282+github-actions[bot]@users.noreply.github.com''

        git add .

        git commit -am "Release version ${{ steps.read-version.outputs.version }}"

        git push'
name: Pre Release Step
on:
  repository_dispatch:
    types: trigger-ga___pre-release-step.yml
