jobs:
  publish:
    name: Publish Repository
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      name: Publish
      run: ./gradlew test publish
name: Publish
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
