jobs:
  release:
    name: Create Release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      id: read-version
      name: Read Version
      run: 'version=`cat gradle.properties | sed -n "s/^.*version\s*=\s*\(\S*\).*$/\1/p"`

        echo "::set-output name=version::$version"

        '
    - continue-on-error: true
      id: generate-changelog
      name: Generate Changelog
      run: 'changelog=`./gradlew generateChangelog`

        echo "::set-output name=changelog::$changelog"

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create_release
      if: ${{ !endsWith(steps.read-version.outputs.version, 'SNAPSHOT') }}
      name: Create Release
      uses: actions/create-release@v1
      with:
        body: '${{ steps.generate-changelog.outputs.changelog }}

          '
        draft: true
        prerelease: false
        release_name: v${{ steps.read-version.outputs.version }}
        tag_name: v${{ steps.read-version.outputs.version }}
    - continue-on-error: true
      if: ${{ !endsWith(steps.read-version.outputs.version, 'SNAPSHOT') }}
      name: Update Release Version
      run: './gradlew test incrementVersion

        git config --global user.name ''github-actions[bot]''

        git config --global user.email ''41898282+github-actions[bot]@users.noreply.github.com''

        git checkout -b release-v${{ steps.read-version.outputs.version }}

        git add gradle.properties

        git commit -am "Increment patch version and append -SNAPSHOT suffix"

        git push --set-upstream origin release-v${{ steps.read-version.outputs.version
        }}

        '
    - continue-on-error: true
      id: cpr
      if: ${{ !endsWith(steps.read-version.outputs.version, 'SNAPSHOT') }}
      name: Create Release Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        assignees: Bastian
        author: 41898282+github-actions[bot]@users.noreply.github.com
        base: master
        body: 'Release report v${{ steps.read-version.outputs.version }}

          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request

          '
        branch: release-v${{ steps.read-version.outputs.version }}
        commit-message: Add Release v${{ steps.read-version.outputs.version }}
        committer: github-actions[bot]
        delete-branch: true
        draft: false
        labels: 'release

          automated pr

          '
        reviewers: Bastian
        signoff: false
        team-reviewers: 'owners

          maintainers

          '
        title: Release v${{ steps.read-version.outputs.version }}
    - continue-on-error: true
      if: steps.cpr.outputs.pull-request-operation == 'created'
      name: Auto Approve Release Pull Request
      uses: juliangruber/approve-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.cpr.outputs.pull-request-number }}
    - continue-on-error: true
      if: steps.cpr.outputs.pull-request-operation == 'created'
      name: Enable Release Pull Request Automerge
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        merge-method: squash
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
name: Release and Update
on:
  repository_dispatch:
    types: trigger-ga___release.yml
